version: '2'
services:
  mongodb:
    image: mongo
    ports:
      - "27017:27017"
  redis:
    image: redis
    ports:
      - "6379:6379"
  cqrs-domain:
    build: ./domain
    depends_on:
      - mongodb
      - redis
    environment:
      WAIT_HOSTS: redis:6379, mongodb:27017
  cqrs-host:
    build: ./host
    depends_on:
      - mongodb
      - redis
    environment:
      WAIT_HOSTS: redis:6379, mongodb:27017
