version: '2'
services:
  redis:
    image: redis
    ports:
      - "6379:6379"
  cqrs-domain:
    build: ./domain
    depends_on:
      - redis
    links:
      - redis
    environment:
      WAIT_HOSTS: redis:6379
  cqrs-host:
    build: ./host
    ports:
      - "3000:3000"
    depends_on:
      - redis
    links:
      - redis
    environment:
      WAIT_HOSTS: redis:6379
